### ISSUE TITLE
AppleDouble finding not working

### ISSUE THREAD

**Issue by nkrabben** [amiaopensource/grabbags#23]
Current code matches pattern against full path instead of filename

https://github.com/amiaopensource/grabbags/blob/1ad421cefc4902b978e750941fdda9a600017e5c/grabbags/utils.py#L39

fix is in #21

**Comment by jfarbowitz** [comment]
Is this still a bug?

**Comment by jfarbowitz** [comment]
It worked in the last test I did. Closing.
