### ISSUE TITLE
Select GUI Tools 

### ISSUE THREAD

**Issue by jfarbowitz** [amiaopensource/grabbags#36]
Created this issue to discuss which GUI tools to use

**Comment by henryborchers** [comment]
There is a qt-gui branch for evaluation. 

To activate, run the grabbags command with the --gui flag

**Note**: 
The "--gui" option is not in the --help  and it is only accessible if you have pyside2 installed in your python environment or grabbags is installed with the [GUI] extras.
See here: https://packaging.python.org/tutorials/installing-packages/#installing-setuptools-extras

**Comment by jfarbowitz** [comment]
It seems like we are going with qt for the time being. Closing.
